// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "e6d5da69b4352246f4c9af6db797a7f0"
    },
    {
        "url": "icon-96.png",
        "revision": "bc795da2e1aadf04cf7c06cd5271bf2a"
    },
    {
        "url": "icon-128.png",
        "revision": "390ee4159b7083d1d0d71bc9785896c5"
    },
    {
        "url": "icon-144.png",
        "revision": "8d8a3b7bb3ac6bac526960452adae32b"
    },
    {
        "url": "icon-152.png",
        "revision": "23718f36722fd2bacfdfce0b7b387917"
    },
    {
        "url": "icon-192.png",
        "revision": "b1dad41d690ae853ee94ae4ca7bcecf9"
    },
    {
        "url": "icon-384.png",
        "revision": "12733b8b79bba21324ee8f5892056183"
    },
    {
        "url": "icon-512.png",
        "revision": "79cf656a0d5527bd318370d8a4ef1e3c"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "adhan.umd.min.js",
        "revision": "3d1e269055e0297fa0dc2b320e9ca36f"
    },
    {
        "url": "app.js",
        "revision": "ae9742c1ef9e3cd956b5f183d4eaf578"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.py",
        "revision": "912a9d55d74613b8f4f07180d0df1fd3"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for php file.py",
        "revision": "6f204d68894960c2efd7b6379cfbddab"
    },
    {
        "url": "db.sql",
        "revision": "3a8a91d738c617c4413012d29ede3978"
    },
    {
        "url": "favicon.ico",
        "revision": "2ccb4c012761e3643dd2663117902357"
    },
    {
        "url": "hadith.php",
        "revision": "d1d35364a7048a09baaa0990ef683bf6"
    },
    {
        "url": "index.html",
        "revision": "9fdabd4c20257e2d3d5ef8faefa8e99e"
    },
    {
        "url": "index.php",
        "revision": "811fd9ab739afc8f9d6873c4fc57cd91"
    },
    {
        "url": "logo.jpg",
        "revision": "3c0de7adc79832d52f005d2c5db797b3"
    },
    {
        "url": "logo2.jpg",
        "revision": "7cab1f1374819dd82edc42d6a207be77"
    },
    {
        "url": "manifest.json",
        "revision": "ab9e19d667c4ced63e6c2d6af270da64"
    },
    {
        "url": "offline.html",
        "revision": "8f26b38cf3f9126c6a161c45ddd6301c"
    },
    {
        "url": "prophet_islamic_hub_data.json",
        "revision": "384261d2d0e8422e41c509304a9f061a"
    },
    {
        "url": "quran.php",
        "revision": "6db15a1c1b47e93343a6667c8325186d"
    },
    {
        "url": "readme file for index.pdf",
        "revision": "5d63f3564ad854e19d43f60743b670d9"
    },
    {
        "url": "readme file for index.php.docx",
        "revision": "6cdcb7cb344a3a06da2f677dc21f4430"
    },
    {
        "url": "sw.js",
        "revision": "218edf8df02e4f71ef6c3927f9231e0d"
    },
    {
        "url": "sessions/sess_du8klafn3ios2gl1c074qa0136",
        "revision": "d41d8cd98f00b204e9800998ecf8427e"
    },
    {
        "url": "sessions/sess_ebr9s0nik9vm1hbnmh5r1629ij",
        "revision": "d41d8cd98f00b204e9800998ecf8427e"
    },
    {
        "url": "sessions/sess_enaojv0tv3sr99slhmketa0b1h",
        "revision": "a73f9468277063dfa9a5b8472d6c16ee"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}